###########
# GENERAL #
###########


[general]
import = [
    "~/.config/alacritty/themes/themes/moonfly.toml"
    # "~/.config/alacritty/rose-pine.toml"
]
live_config_reload = true

[env]
[window]
padding = {x = 5, y = 5}
opacity = 0.8
decorations = "Buttonless"
option_as_alt = "OnlyLeft"

[font]
# brew install --cask font-jetbrains-mono
# fc-list | grep -i nerd
normal = { family = "Hack Nerd Font", style="Regular" }
bold = { style = "Bold" }  # Inherits family from normal, Default style: Bold
italic = { style = "Italic" }  # Inherits family from normal, Default style: Italic
bold_italic = { style = "Bold Italic" }  # Inherits family from normal, Default style: Bold Italic
size = 13  # Default: 11.25
# Offset is extra space around each character
offset = { x = 0, y = 0 }  # Default: x = 0, y = 0
# Glyph offset determines the locations of the glyphs within their cells
glyph_offset = { x = 0, y = 0 }  # Default: x = 0, y = 0
# Use built-in font for box drawing characters
builtin_box_drawing = true  # Default: true

[scrolling]
# Maximum number of lines in the scrollback buffer
history = 10000  # Default: 10000
# Number of lines scrolled for every input scroll increment
multiplier = 3  # Default: 3
